from pydantic import BaseModel
from typing import Optional

# 1. Model for new user registration input
class UserRegister(BaseModel):
    """Data received when a user signs up."""
    username: str
    password: str

# 2. Model for user login input
class UserLogin(BaseModel):
    """Data received when a user attempts to log in."""
    username: str
    password: str

# 3. Model for the user record as stored in the database
class UserInDB(BaseModel):
    """The data model for a user record retrieved from the database."""
    id: Optional[int] = None  # Optional because ID is generated by the database
    username: str
    password_hash: str        # Store the securely hashed password, NOT the raw password